import jsPDF from "jspdf";

export function generateWithdrawalPDF(passbookData, intentData) {
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.setFont(undefined, "bold");
  doc.text("BANKMATE DEMO BANK", 105, 20, { align: "center" });

  doc.setFontSize(14);
  doc.text("WITHDRAWAL FORM", 105, 30, { align: "center" });

  doc.setFontSize(10);
  doc.setFont(undefined, "italic");
  doc.text("For demonstration purposes only", 105, 37, { align: "center" });

  doc.setDrawColor(200);
  doc.line(20, 42, 190, 42);

  doc.setFontSize(12);
  doc.setFont(undefined, "normal");

  let y = 55;
  const lineGap = 12;

  doc.text(`Account Holder:`, 20, y);
  doc.text(`${passbookData.accountHolder}`, 90, y);
  y += lineGap;

  doc.text(`Account Number:`, 20, y);
  doc.text(`XXXX XXXX ${passbookData.accountNumber.slice(-4)}`, 90, y);
  y += lineGap;

  doc.text(`Branch:`, 20, y);
  doc.text(`${passbookData.branch}`, 90, y);
  y += lineGap;

  doc.text(`IFSC:`, 20, y);
  doc.text(`${passbookData.ifsc}`, 90, y);
  y += lineGap * 1.5;

  doc.setFont(undefined, "bold");
  doc.text(`Withdrawal Amount:`, 20, y);
  doc.text(`Rs. ${intentData.amount.toLocaleString("en-IN")}`, 90, y);
  doc.setFont(undefined, "normal");
  y += lineGap * 2;

  doc.text("Signature:", 20, y);
  doc.line(60, y, 190, y); // blank signature line

  y += 20;
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text(
    "Generated by BankMate — a banking paperwork assistant. Not a real transaction.",
    105,
    280,
    { align: "center" }
  );

  return doc;
}

export function generateMobileUpdatePDF(passbookData, newMobileNumber) {
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.setFont(undefined, "bold");
  doc.text("BANKMATE DEMO BANK", 105, 20, { align: "center" });

  doc.setFontSize(14);
  doc.text("MOBILE NUMBER UPDATE FORM", 105, 30, { align: "center" });

  doc.setFontSize(10);
  doc.setFont(undefined, "italic");
  doc.text("For demonstration purposes only", 105, 37, { align: "center" });

  doc.setDrawColor(200);
  doc.line(20, 42, 190, 42);

  doc.setFontSize(12);
  doc.setFont(undefined, "normal");

  let y = 55;
  const lineGap = 12;

  doc.text(`Account Holder:`, 20, y);
  doc.text(`${passbookData.accountHolder}`, 90, y);
  y += lineGap;

  doc.text(`Account Number:`, 20, y);
  doc.text(`XXXX XXXX ${passbookData.accountNumber.slice(-4)}`, 90, y);
  y += lineGap * 1.5;

  doc.setFont(undefined, "bold");
  doc.text(`New Mobile Number:`, 20, y);
  doc.text(`${newMobileNumber}`, 90, y);
  doc.setFont(undefined, "normal");
  y += lineGap * 2;

  doc.text("Signature:", 20, y);
  doc.line(60, y, 190, y);

  y += 20;
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text(
    "Generated by BankMate — a banking paperwork assistant. Not a real transaction.",
    105,
    280,
    { align: "center" }
  );

  return doc;
}